# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app


# Run Python script when the container launches
CMD ["python", "hello_name.py"]