# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy all the files to the directory in the container
COPY . /app


# Run Python script when the container launches
CMD ["python", "hello_name.py"]